# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  vdms-dataprep:
    build:
      target: ${DEV_BUILD_TARGET:-final-dev}
      args:
        - COVERAGE_REQ
    image: ${REGISTRY}vdms-dataprep:latest-final-dev
    environment:
      - DEFAULT_BUCKET_NAME=vdms-bucket-test
      - DB_COLLECTION=video-rag-dev
    volumes:
      - "..:/app"