# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  audio-analyzer:
    devices:
      - /dev/dxg:/dev/dxg
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl:ro
    environment:
      AUDIO_ANALYZER__MODELS__ASR__DEVICE: ${VOICE_ASR_DEVICE:-GPU}
