x-vippet: &vippet
  image: docker.io/intel/vippet-app:v1.0.0
  build:
    context: .
    dockerfile: Dockerfile.vippet
  ports:
    - "7860:7860"
  command: gradio app.py
  depends_on:
    - models
  restart: on-failure:5
  # # The following config applies to WSL2:
  # environment:
  #   DISPLAY: ":0"
  #   WAYLAND_DISPLAY: "wayland-0"
  #   XDG_RUNTIME_DIR: "/mnt/wslg/runtime-dir"
  #   PULSE_SERVER: "/mnt/wslg/PulseServer"
  #   GST_DEBUG: "1"
  # devices:
  #   - "/dev/dri:/dev/dri"
  # volumes:
  #   - "/run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix"
  #   - "/run/desktop/mnt/host/wslg:/mnt/wslg"
  #   - "/usr/lib/wsl:/usr/lib/wsl"
  # The following config applies to Linux:
  environment:
    GST_DEBUG: "1"
    TZ: America/Los_Angeles
  volumes:
    - collector-signals:/home/dlstreamer/vippet/.collector-signals
    - ./models:/home/dlstreamer/vippet/models

services:
  models:
    image: docker.io/intel/dlstreamer:2025.0.1.3-ubuntu24
    container_name: models
    volumes:
      - ./models/:/output
      - ./models.sh:/tmp/models.sh
    environment:
      - MODELS_PATH=/output/
    user: root
    command: bash -xc '
        cp /tmp/models.sh . &&
        chmod +x models.sh &&
        bash -cx ./models.sh &&
        tail -f /dev/null
      '
    restart: on-failure:5
  vippet-cpu:
    <<: *vippet
    container_name: vippet-cpu
    profiles: [cpu]
  vippet-gpu:
    <<: *vippet
    container_name: vippet-gpu
    group_add:
     - "110"
    devices:
      - "/dev/dri:/dev/dri"
    profiles: [gpu]
  vippet-npu:
    <<: *vippet
    container_name: vippet-npu
    group_add:
     - "110"
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/accel:/dev/accel"
    profiles: [npu]
  collector:
    image: docker.io/intel/vippet-collector:v1.0.0
    build:
      context: ./collector
      dockerfile: Dockerfile
    container_name: collector
    privileged: true
    devices:
      - "/sys:/sys"
      - "/dev:/dev"
      - "/run:/run"
      - "/proc:/proc"
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - ./collector/telegraf.conf:/etc/telegraf/telegraf.conf
      - "collector-signals:/app/.collector-signals"
    restart: on-failure:5
  videogenerator:
    image: docker.io/intel/vippet-videogenerator:v1.0.0
    build:
      context: video_generator
      dockerfile: Dockerfile
    container_name: videogenerator
    volumes:
      - "./videos:/usr/src/app/output"
      - "./video_generator/config.json:/usr/src/app/config.json"
      - "./video_generator/background.gif:/usr/src/app/background.gif"
      - "./video_generator/images:/usr/src/app/images"
    restart: on-failure:5

volumes:
  collector-signals:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
