[tool.poetry]
name = "model_download"
version = "0.1.0"
description = "A FastAPI application for downloading and converting HuggingFace/Ollama models."
authors = []
packages = [{ include = "app" }]

[tool.poetry.dependencies]
einops = "^0.8.1"
fastapi = "0.115.4"
huggingface-hub = { version = "^0.30.0", extras = ["hf-transfer"] }
nncf = "2.16.0"
openvino = "2025.1.0"
openvino-tokenizers = { version = "2025.1.0", extras = ["transformers"] }
optimum = {extras = ["openvino", "nncf"], version = "^1.25.0"}
pillow = "^11.2.1"
python = "^3.10"
pydantic = "^1.10.13"
qwen_vl_utils = "^0.0.11"
sentence_transformers = "3.1.1"
structlog = "25.1.0"
transformers = "^4.51.3"
uvicorn = "^0.23.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.21.1"
httpx = "^0.24.1"
pytest-mock = "^3.11.1"

[tool.poetry.group.cpu.dependencies]
torch = { version = "^2.7.1", source = "pytorch-cpu" }

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=app --cov-report=term-missing"

[build-system]
requires = ["poetry-core>=1.8.3"]
build-backend = "poetry.core.masonry.api"