apiVersion: v1
kind: Service
metadata:
  name: "videosearch"
spec:
  type: {{ .Values.videosearch.service.type }}
  ports:
    - port: {{ .Values.videosearch.service.port }}
      targetPort: {{ .Values.videosearch.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "videosearch.name" . }}
