apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.audiointelligence.volumeMounts.pvcName }}
  annotations:
    helm.sh/resource-policy: keep  # Prevent Helm from deleting PVC on uninstall
spec:
  accessModes:
    - {{ .Values.audiointelligence.volumeMounts.egai_audio_intelligence_pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.audiointelligence.volumeMounts.egai_audio_intelligence_pvc.size }}