apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.audiointelligence.name }}
  labels:
    app: {{ include "audiointelligence.name" . }}
spec:
  type: {{ .Values.audiointelligence.service.type }}
  selector:
    app: {{ .Values.audiointelligence.name }}
  ports:
    - port: {{ .Values.audiointelligence.service.port }}
      targetPort: {{ .Values.audiointelligence.service.targetPort }}