# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# UI services required in Dual UI and Unified UI Setup for Video Search and Summarization.
services:
  nginx:
    depends_on:
      vss-search-ui:
        condition: service_started
        required: false
      vss-summary-ui:
        condition: service_started
        required: false
      vss-unified-ui:
        condition: service_started
        required: false
      
  vss-summary-ui:
    build:
      context: ../ui/react
      dockerfile: Dockerfile
    image: ${REGISTRY:-}vss-ui:${TAG:-latest}
    ipc: host
    profiles:
      - dual_ui
    environment:
      no_proxy: ${no_proxy},${HOST_IP},${PM_HOST},minio-service,localhost
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      APP_ENDPOINT_URL: ${UI_PM_ENDPOINT}
      APP_ASSETS_URL: ${UI_ASSETS_ENDPOINT}
      APP_FEATURE_MUX: ${APP_FEATURE_MUX:-ATOMIC}
      APP_SOCKET_APPEND: ${CONFIG_SOCKET_APPEND:-CONFIG_OFF}
      APP_SUMMARY_FEATURE: FEATURE_ON
      APP_SEARCH_FEATURE: FEATURE_OFF
    depends_on:
      pipeline-manager:
        condition: service_started
    restart: unless-stopped
    networks:
      - vs_network

  vss-search-ui:
    build:
      context: ../ui/react
      dockerfile: Dockerfile
    image: ${REGISTRY:-}vss-ui:${TAG:-latest}
    ipc: host
    profiles:
      - dual_ui
    environment:
      no_proxy: ${no_proxy},${HOST_IP},${PM_HOST},minio-service,localhost
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      APP_ENDPOINT_URL: ${UI_PM_ENDPOINT}
      APP_ASSETS_URL: ${UI_ASSETS_ENDPOINT}
      APP_FEATURE_MUX: ${APP_FEATURE_MUX:-ATOMIC}
      APP_SOCKET_APPEND: ${CONFIG_SOCKET_APPEND:-CONFIG_OFF}
      APP_SUMMARY_FEATURE: FEATURE_OFF
      APP_SEARCH_FEATURE: FEATURE_ON
    depends_on:
      pipeline-manager:
        condition: service_started
    restart: unless-stopped
    networks:
      - vs_network

  vss-unified-ui:
    build:
      context: ../ui/react
      dockerfile: Dockerfile
    image: ${REGISTRY:-}vss-ui:${TAG:-latest}
    ipc: host
    profiles:
      - unified_ui
    environment:
      no_proxy: ${no_proxy},${HOST_IP},${PM_HOST},minio-service,localhost
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      APP_ENDPOINT_URL: ${UI_PM_ENDPOINT}
      APP_ASSETS_URL: ${UI_ASSETS_ENDPOINT}
      APP_FEATURE_MUX: ${APP_FEATURE_MUX:-ATOMIC}
      APP_SOCKET_APPEND: ${CONFIG_SOCKET_APPEND:-CONFIG_OFF}
      APP_SUMMARY_FEATURE: FEATURE_ON
      APP_SEARCH_FEATURE: FEATURE_ON
    depends_on:
      pipeline-manager:
        condition: service_started
    restart: unless-stopped
    networks:
      - vs_network