#!/usr/bin/env python3
"""
Scaffold an OVMS/OpenVINO model directory for the VSS sample application.

This helper mirrors the actual Qwen example layout in:
  config/ovms_config/models/Qwen_Qwen2.5-VL-3B-Instruct_CPU_int8

It is intentionally conservative:
- By default it copies structural text/config files from the Qwen example so a
  developer can see the required layout, but those files must be replaced or
  edited to match the new model.
- It creates `.PENDING` marker files for expected OpenVINO IR artifacts instead
  of fake `.xml`/`.bin` files, because fake IR files can make OVMS fail in
  confusing ways.
- With `--run-conversion`, it invokes the documented optimum-intel/OpenVINO
  conversion path. The required packages are not imported at module import time;
  install them in your own virtual environment first.

Typical usage from APP_ROOT:

  python3 skills/vss-model-onboarding/scripts/prepare_ovms_model.py \
    --source-model Qwen/Qwen2.5-VL-3B-Instruct \
    --model-name Qwen_Qwen2.5-VL-3B-Instruct_CPU_int8 \
    --device CPU \
    --precision int8

Optional conversion path:

  python3 skills/vss-model-onboarding/scripts/prepare_ovms_model.py \
    --source-model <hf-id-or-local-path> \
    --model-name <storage-model-name> \
    --run-conversion

Install conversion tools separately, for example:
  python3 -m pip install optimum-intel[openvino] openvino-tokenizers
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from pathlib import Path
from typing import Iterable

APP_ROOT = Path(__file__).resolve().parents[3]
MODELS_ROOT = APP_ROOT / "config" / "ovms_config" / "models"
QWEN_EXAMPLE = MODELS_ROOT / "Qwen_Qwen2.5-VL-3B-Instruct_CPU_int8"
OVMS_CONFIG = MODELS_ROOT / "config.json"

TEXT_FILES_TO_COPY = [
    "graph.pbtxt",
    "config.json",
    "openvino_config.json",
    "generation_config.json",
    "preprocessor_config.json",
    "video_preprocessor_config.json",
    "chat_template.jinja",
    "tokenizer_config.json",
    "special_tokens_map.json",
    "added_tokens.json",
    "tokenizer.json",
    "vocab.json",
    "merges.txt",
]

EXPECTED_IR_BASENAMES = [
    "openvino_language_model",
    "openvino_text_embeddings_model",
    "openvino_vision_embeddings_model",
    "openvino_vision_embeddings_merger_model",
    "openvino_tokenizer",
    "openvino_detokenizer",
]


def sanitize_storage_name(source_model: str, device: str, precision: str, *, openvino_namespace: bool = False) -> str:
    """Match the storage naming convention used by setup.sh."""
    sanitized = re.sub(r"[^A-Za-z0-9_.-]", "_", source_model)
    if openvino_namespace or source_model.startswith("OpenVINO/"):
        return f"{sanitized}_{device}"
    return f"{sanitized}_{device}_{precision}"


def copy_template_files(destination: Path, overwrite: bool) -> None:
    if not QWEN_EXAMPLE.is_dir():
        raise FileNotFoundError(f"Qwen example directory not found: {QWEN_EXAMPLE}")
    destination.mkdir(parents=True, exist_ok=True)

    for name in TEXT_FILES_TO_COPY:
        source = QWEN_EXAMPLE / name
        target = destination / name
        if not source.exists():
            continue
        if target.exists() and not overwrite:
            continue
        shutil.copy2(source, target)


def patch_graph(destination: Path, device: str, cache_size: int | None) -> None:
    graph = destination / "graph.pbtxt"
    if not graph.exists():
        return
    text = graph.read_text(encoding="utf-8")
    text = re.sub(r'device:\s*"[^"]+"', f'device: "{device}"', text)
    if cache_size is not None:
        text = re.sub(r"cache_size:\s*\d+", f"cache_size: {cache_size}", text)
    graph.write_text(text, encoding="utf-8")


def create_pending_markers(destination: Path) -> None:
    for base in EXPECTED_IR_BASENAMES:
        for suffix in ("xml", "bin"):
            real_file = destination / f"{base}.{suffix}"
            marker = destination / f"{base}.{suffix}.PENDING"
            if not real_file.exists() and not marker.exists():
                marker.write_text(
                    f"Replace this marker with the real {base}.{suffix} generated by OpenVINO conversion.\n",
                    encoding="utf-8",
                )


def register_model(model_name: str, destination: Path) -> None:
    OVMS_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    if OVMS_CONFIG.exists():
        data = json.loads(OVMS_CONFIG.read_text(encoding="utf-8"))
    else:
        data = {"model_config_list": []}

    base_path = destination.relative_to(OVMS_CONFIG.parent).as_posix()
    entries = data.setdefault("model_config_list", [])
    for entry in entries:
        config = entry.setdefault("config", {})
        if config.get("name") == model_name:
            config["base_path"] = base_path
            break
    else:
        entries.append({"config": {"name": model_name, "base_path": base_path}})

    OVMS_CONFIG.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def run_conversion(source_model: str, destination: Path, precision: str, extra_args: Iterable[str]) -> None:
    """Run optimum-cli and tokenizer conversion if the tools are available."""
    if shutil.which("optimum-cli") is None:
        raise RuntimeError("optimum-cli not found. Install optimum-intel[openvino] in your active environment.")

    command = [
        "optimum-cli",
        "export",
        "openvino",
        "--model",
        source_model,
        "--weight-format",
        precision,
        "--trust-remote-code",
        *extra_args,
        str(destination),
    ]
    subprocess.run(command, check=True)

    if not (destination / "openvino_detokenizer.xml").exists():
        if shutil.which("convert_tokenizer") is None:
            raise RuntimeError("convert_tokenizer not found. Install openvino-tokenizers in your active environment.")
        subprocess.run(
            [
                "convert_tokenizer",
                "--with-detokenizer",
                "--trust-remote-code",
                "-o",
                str(destination),
                source_model,
            ],
            check=True,
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scaffold a VSS OVMS model directory.")
    parser.add_argument("--source-model", required=True, help="HF model id or local model path.")
    parser.add_argument("--model-name", help="Storage directory/model name. Defaults to setup.sh naming convention.")
    parser.add_argument("--device", default="CPU", help="OVMS target device, e.g. CPU, GPU, NPU, HETERO:CPU,GPU.")
    parser.add_argument("--precision", default="int8", help="OpenVINO weight format, e.g. int8 or int4.")
    parser.add_argument("--cache-size", type=int, default=None, help="Optional graph.pbtxt cache_size override in GB.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite copied template files if they already exist.")
    parser.add_argument("--register", action="store_true", help="Add/update this model in config/ovms_config/models/config.json.")
    parser.add_argument("--run-conversion", action="store_true", help="Run optimum-cli export openvino into the destination.")
    parser.add_argument(
        "--extra-optimum-arg",
        action="append",
        default=[],
        help="Extra argument passed to optimum-cli. Repeat for multiple tokens, e.g. --extra-optimum-arg=--task --extra-optimum-arg=text-generation-with-past.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    model_name = args.model_name or sanitize_storage_name(args.source_model, args.device, args.precision)
    destination = MODELS_ROOT / model_name

    copy_template_files(destination, args.overwrite)
    patch_graph(destination, args.device, args.cache_size)

    if args.run_conversion:
        run_conversion(args.source_model, destination, args.precision, args.extra_optimum_arg)
    else:
        create_pending_markers(destination)

    if args.register:
        register_model(model_name, destination)

    print(f"Scaffolded: {destination}")
    print("Review copied Qwen metadata and replace it with the new model's real files before serving.")
    if not args.register:
        print("Not registered. Re-run with --register or edit config/ovms_config/models/config.json manually.")


if __name__ == "__main__":
    main()
