# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  retriever-milvus:
    image: ${REGISTRY:-}retriever-milvus:${TAG:-latest}
    container_name: retriever-milvus
    ports:
      - "${RETRIEVER_SERVICE_PORT}:7770"
    ipc: host
    environment:
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - DEVICE=${DEVICE}
      - LOCAL_EMBED_MODEL_ID=${LOCAL_EMBED_MODEL_ID}
      - MODEL_DIR=${MODEL_DIR}
      - MILVUS_HOST=${MILVUS_HOST}
      - MILVUS_PORT=${MILVUS_PORT}
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - ${USER_GROUP_ID-1000} 
      - ${VIDEO_GROUP_ID}    
      - ${RENDER_GROUP_ID}    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$RETRIEVER_SERVICE_PORT/v1/retrieval/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 30
      start_period: 30s
    networks:
      - default
    volumes:
      - $HOME/.cache/huggingface:/home/user/.cache/huggingface:rw
      - ${MODEL_DIR}:/home/user/models:rw

networks:
  default:
    driver: bridge