global:
  huggingface:
    apiToken: <huggingfacehub-api-token># Set this during installation
  proxy:
    no_proxy: <no-proxy>
    http_proxy: <http-proxy>
    https_proxy: <https-proxy>
  POSTGRES_USER: <postgres-user>
  POSTGRES_PASSWORD: <postgres-password>
  EMBEDDING_MODEL_NAME: <embedding-model-name>
  teiEmbeddingService:
    enabled: false
  ovmsEmbeddingService:
    enabled: false

dataprepPgvector:
  name: document-ingestion
  image:
    repository: intel/document-ingestion
    tag: "1.1.1"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  env:
    PG_CONNECTION_STRING: postgresql+psycopg://
    PORT_DB: 5432/langchain
    INDEX_NAME: intel-rag
    DATASTORE_ENDPOINT_URL: http://datastore
    CHUNK_SIZE: 1500
    CHUNK_OVERLAP: 100
