global:
  huggingface:
    apiToken:  # Set this during installation
  proxy:
    no_proxy: 
    http_proxy: 
    https_proxy: 
  POSTGRES_USER: 
  POSTGRES_PASSWORD: 
  EMBEDDING_MODEL_NAME: 
  teiEmbeddingService:
    enabled: false
  ovmsEmbeddingService:
    enabled: false

dataprepPgvector:
  name: document-ingestion
  image:
    repository: intel/document-ingestion
    tag: "1.1.1"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  env:
    PG_CONNECTION_STRING: postgresql+psycopg://
    PORT_DB: 5432/langchain
    INDEX_NAME: intel-rag
    DATASTORE_ENDPOINT_URL: http://datastore
    CHUNK_SIZE: 1500
    CHUNK_OVERLAP: 100
