apiVersion: v2
name: video-search-and-summarization
description: A helm chart for deploying Intel Video Search and Summarization sample application
version: 1.1.2
dependencies:
  - name: ovms
    version: 0.1.0
    repository: "file://subchart/ovms"
    condition: ovms.enabled
  - name: minioServer
    version: 0.1.0
    repository: "file://subchart/minioserver"
  - name: audioanalyzer
    version: 0.1.0
    repository: "file://subchart/audio-analyzer/"
    condition: audioanalyzer.enabled
  - name: postgresql
    version: 0.1.0
    repository: "file://subchart/postgresql/"
  - name: rabbitmq
    version: 0.1.0
    repository: "file://subchart/rabbitmq/"
    condition: rabbitmq.enabled
  - name: videoingestion
    version: 0.1.0
    repository: "file://subchart/videoingestion/"
    condition: videoingestion.enabled
  - name: videosummaryui
    version: 0.1.0
    repository: "file://subchart/videosummaryui/"
  - name: vlminference
    version: 0.1.0
    repository: "file://subchart/vlminference/"
    condition: vlminference.enabled
  - name: videosearch
    version: 0.1.0
    repository: "file://subchart/videosearch/"
    condition: videosearch.enabled
  - name: vdmsvectordb
    version: 0.1.0
    repository: "file://subchart/vdms-vectordb/"
    condition: vdmsvectordb.enabled
  - name: vdmsdataprep
    version: 0.1.0
    repository: "file://subchart/vdms-dataprep/"
    condition: vdmsdataprep.enabled
  - name: multimodalembeddingms
    version: 0.1.0
    repository: "file://subchart/multimodal-embedding-ms/"
    condition: multimodalembeddingms.enabled