rabbitmq:
  enabled: true
ovms:
  enabled: true
videoingestion:
  enabled: true
audioanalyzer:
  enabled: true

summaryui:
  enabled: true
  name: vss-summary-ui
  feature:
    summary: "FEATURE_ON"
    search: "FEATURE_OFF"
    mux: "ATOMIC"
