global:
  proxy:
    no_proxy: <no-proxy>
    http_proxy: <http-proxy>
    https_proxy: <https-proxy>

chatqnaui:
  name: chatqna-ui
  image:
    repository: intel/chatqna-ui
    tag: "1.1.2"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  env:
    APP_ENDPOINT_URL: "/v1/chatqna"
    APP_DATA_PREP_URL: "/v1/dataprep"
