# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: ${PROJECT_NAME:-object-store}
services:
  minio-server:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    ports:
      - "${MINIO_API_HOST_PORT:-9000}:${MINIO_API_PORT:-9000}"
      - "${MINIO_CONSOLE_HOST_PORT:-9001}:${MINIO_CONSOLE_PORT:-9001}"
    volumes:
      - "${MINIO_MOUNT_PATH:-/mnt/miniodata}:/data"
    command: |
      server /data
      --address ":${MINIO_API_PORT:-9000}"
      --console-address ":${MINIO_CONSOLE_PORT:-9001}"

  data-store:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: prod
    image: intel/object-store:1.1
    hostname: data_store
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - MINIO_HOST=${MINIO_HOST:-minio-server}
      - MINIO_API_PORT=${MINIO_API_PORT:-9000}
      # Raise error if following required env vars is not set
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:?error}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:?error}
    ports:
      - "${DATASTORE_HOST_PORT:-8888}:8000"
    depends_on:
      - minio-server

networks:
  default:
    driver: bridge
