apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-model-download
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: model-download
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: "1"
            - name: HF_TOKEN
              value: "{{ .Values.env.HF_TOKEN }}"
            - name: MODEL_PATH
              value: "/opt/models"
            - name: ENABLED_PLUGINS
              value: "{{ .Values.env.ENABLED_PLUGINS }}"
          command: ["--plugins", "{{ .Values.env.ENABLED_PLUGINS | default "all" }}"]
          volumeMounts:
            - name: models
              mountPath: /opt/models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: models-pvc