apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-model-download
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: model-download
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          env:
            - name: HTTP_PROXY
              value: "{{ .Values.global.proxy.http_proxy }}"
            - name: HTTPS_PROXY
              value: "{{ .Values.global.proxy.https_proxy }}"
            - name: NO_PROXY
              value: "{{ .Values.global.proxy.no_proxy }}"
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: "1"
            - name: HF_TOKEN
              value: "{{ .Values.env.HUGGINGFACEHUB_API_TOKEN }}"
            - name: MODEL_PATH
              value: "/opt/models"
            - name: ENABLED_PLUGINS
              value: "{{ .Values.env.ENABLED_PLUGINS }}"
          command: ["/opt/entrypoint.sh"]
          args: ["--plugins", "{{ .Values.env.ENABLED_PLUGINS | default "all" }}"]
          volumeMounts:
            - name: models
              mountPath: /opt/models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: models-pvc