{{- include "chatqna-core.validateGpuSettings" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatqna-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatqna-core
  template:
    metadata:
      labels:
        app: chatqna-core
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: chatqna-core
          image: "{{ if .Values.gpu.enabled }}{{ .Values.image.registry }}chatqna:{{ .Values.image.backendGpuTag }}{{ else }}{{ .Values.image.registry }}chatqna:{{ .Values.image.backendTag }}{{ end }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
            privileged: false
          readinessProbe:
            httpGet:
              path: {{ .Values.chatqna.readinessProbe.httpGet.path }}
              port: {{ .Values.chatqna.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.chatqna.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.chatqna.readinessProbe.periodSeconds }}
          env:
            - name: http_proxy
              value: "{{ .Values.global.http_proxy }}"
            - name: https_proxy
              value: "{{ .Values.global.https_proxy }}"
            - name: no_proxy
              value: "{{ .Values.global.no_proxy }}"
            - name: HF_ACCESS_TOKEN
              value: "{{ .Values.global.huggingface.apiToken }}"
          {{ if .Values.gpu.enabled }}
          resources:
            requests:
              {{ .Values.gpu.key}}: 1
            limits:
              {{ .Values.gpu.key}}: 1
          devices:
            - name: dri-device
              containerPath: /dev/dri
          {{ end }}
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: model-cache
              mountPath: "{{ .Values.global.model_cache_path }}"
            {{- if .Values.configmap.enabled }}
            - name: model-config
              mountPath: /tmp/model_config/config.yaml
              subPath: config.yaml
            {{- end }}
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: chatqna-pvc
        {{- if .Values.configmap.enabled }}
        - name: model-config
          configMap:
            name: model-config
        {{- end}}
      {{- if .Values.gpu.enabled }}
        - name: dri-device
          hostPath:
            path: {{ .Values.gpu.devices }}
            type: Directory
      {{- end }}
