apiVersion: v1
kind: Service
metadata:
  name: chatqna-core
spec:
  type: {{ .Values.chatqna.service.type }}
  ports:
    - port: {{ .Values.chatqna.service.port }}
      targetPort: 8888
  selector:
    app: chatqna-core
