apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-pvc
  {{- if .Values.global.keeppvc }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.vllm_pvc.size }}
