apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgvectorContainer.name }}
spec:
  type: {{ .Values.pgvectorContainer.service.type }}
  ports:
    - port: {{ .Values.pgvectorContainer.service.port }}
      targetPort: 5432
  selector:
    app: {{ .Values.pgvectorContainer.name }}