global:
  huggingface:
    apiToken:  # Set this during installation
  proxy:
    no_proxy: 
    http_proxy: 
    https_proxy: 

vllmService:
  name: vllm-service
  image: 
    repository: opea/vllm-openvino
    tag: "1.1"
    pullPolicy: IfNotPresent
  readinessProbe:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 60
    periodSeconds: 30
  service:
    type: ClusterIP
    port: 8080
    targetPort: 80
  env:
    KVCACHE: 50
    TENSOR_PARALLEL_SIZE: 1
    VLLM_OPENVINO_CPU_KV_CACHE_PRECISION: u8
    VLLM_OPENVINO_ENABLE_QUANTIZED_WEIGHTS: ON
    OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: http/protobuf
    OTEL_METRICS_EXPORTER: otlp
    OTEL_TRACES_EXPORTER: otlp
    OTEL_SERVICE_NAME: chatqna
    OTEL_SERVICE_ENV: chatqna
