#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: time-series-analytics-microservice-config
data:
  config.json: |-
{{ .Files.Get "config.json" | indent 4 }}
---


