global:
  huggingface:
    apiToken:   # Set this during installation
  proxy:
    no_proxy: 
    http_proxy: 
    https_proxy: 

tgiService:
  name: text-generation-service
  image: 
    repository: ghcr.io/huggingface/text-generation-inference
    tag: "3.0.1-intel-xpu"
    pullPolicy: IfNotPresent
  readinessProbe:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 60
    periodSeconds: 30
  service:
    type: ClusterIP
    port: 8080
    targetPort: 80
  shm_size: 1g
