global:
  proxy:
    no_proxy: <no-proxy>
    http_proxy: <http-proxy>
    https_proxy: <https-proxy>
  POSTGRES_USER: <postgres-user>
  POSTGRES_PASSWORD: <postgres-passwd>

pgvectorContainer:
  name: pgvector
  image:
    repository: pgvector/pgvector
    tag: pg16
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  env:
    POSTGRES_DB: langchain
