# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: ovmsService
description: A Helm chart for deploying OpenVINO Model Server
type: application
version: 0.1.0
