# Copyright Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: dlstreamer-pipeline-server-config-input
data:
  config.json: |-
{{ .Files.Get "dlstreamer_pipeline_server_config.json" | indent 4 }}