# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  multimodal-embedding-serving:
    image: ${REGISTRY:-}multimodal-embedding-serving:${TAG:-latest}
    container_name: vclip-embedding
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${EMBEDDING_SERVER_PORT}:8000"
    ipc: host
    environment:
      no_proxy_env: ${no_proxy_env},vdms-dataprep-ms
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      MODEL_NAME: ${VCLIP_MODEL}
      DEFAULT_START_OFFSET_SEC: ${DEFAULT_START_OFFSET_SEC}
      DEFAULT_CLIP_DURATION: ${DEFAULT_CLIP_DURATION}
      DEFAULT_NUM_FRAMES: ${DEFAULT_NUM_FRAMES}
      EMBEDDING_DEVICE: ${EMBEDDING_DEVICE}
      EMBEDDING_USE_OV: ${EMBEDDING_USE_OV}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 40
      start_period: 5s
    networks:
      - my_network
    volumes:
      - /home/$USER/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - data-prep:/tmp/dataprep
      - ov-models:/app/ov-models
volumes:
  data-prep:
    external: true
  ov-models:
    external: true
networks:
  my_network:
    driver: bridge
