# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
services:
  data-store:
    build:
      target: dev
    image: intel/object-store:1.1-dev
    environment:
      - DEFAULT_BUCKET=intel.gai.dev.test
      - OBJECT_PREFIX=test
    volumes:
      - "${DATASTORE_CODE_DIR}:/app"
