# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
services:
  dataprep_microservice:
    build:
      target: dev
    image: intel/document-ingestion:1.2.0-dev
    environment:
      DEFAULT_BUCKET: "intel.gai.dev.test"
      OBJECT_PREFIX: "test"
    volumes:
      - "../app:/app/app"
    restart: always
