#
# Apache v2 license
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

services:
  broker:
    image: eclipse-mosquitto
    hostname: mqtt
    container_name: mqtt_broker
    volumes:
      - ../utils/mosquitto:/mosquitto/config
    ports:
      - "1883:1883"
    networks:
      - app_network

  edge-video-analytics-microservice:
    image: intel/edge-video-analytics-microservice:2.4.0
    hostname: edge-video-analytics-microservice
    container_name: edge-video-analytics-microservice
    read_only: true
    security_opt:
      - no-new-privileges
    build:
      context: ..
      target: evam_standard
      args:
        MSGBUS_LIB_VERSION: 4.0.0
        UTILS_LIB_VERSION: 4.0.0
        EVAM_UID: ${EVAM_UID}
        USER: ${EVAM_USER}
        BASE_IMAGE: "ubuntu:22.04"
        CMAKE_INSTALL_PREFIX: "/opt/intel/eii"
        # Download sources for GPL/LGPL/AGPL binary distributed components (yes/no)
        DOWNLOAD_GPL_SOURCES: "no"
        no_proxy: ${no_proxy}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    privileged: false
    tty: true
    entrypoint: ["./run.sh"]
    ports:
      - '8080:8080'
      - '8554:8554'
    networks:
      - app_network
    environment:
      - S3_STORAGE_HOST=${S3_STORAGE_HOST}
      - S3_STORAGE_PORT=${S3_STORAGE_PORT}
      - S3_STORAGE_USER=${S3_STORAGE_USER}
      - S3_STORAGE_PASS=${S3_STORAGE_PASS}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - ENABLE_RTSP=true
      - RTSP_PORT=8554
      - ENABLE_WEBRTC=true
      - WEBRTC_SIGNALING_SERVER=ws://localhost:8443
      - no_proxy=$no_proxy,multimodal-data-visualization-streaming,${RTSP_CAMERA_IP},otel-collector
      - http_proxy=$http_proxy
      - https_proxy=$https_proxy
      - RUN_MODE=EVA
      - GENICAM=Balluff
      - GST_DEBUG=1,gencamsrc:2
      # Default Detection and Classification Device
      - DETECTION_DEVICE=CPU
      - CLASSIFICATION_DEVICE=CPU
      - ADD_UTCTIME_TO_METADATA=true
      - LSFEATURE_NAME="EVAM"
      - RUNTIME_LICENSE_CHECK_FREQ_SECS=${RUNTIME_LICENSE_CHECK_FREQ_SECS}
      - APPLICATION_RESTART_FREQ_SECS=${APPLICATION_RESTART_FREQ_SECS}
      - HTTPS=false # Make it "true" to enable SSL/TLS secure mode, mount the generated certificates
      - MTLS_VERIFICATION=false # if HTTPS=true, enable/disable client certificate verification for mTLS
      # Model Registry Microservice
      - MR_VERIFY_CERT=${MR_VERIFY_CERT}
      # Append pipeline name to a publisher topic
      - APPEND_PIPELINE_NAME_TO_PUBLISHER_TOPIC=false
      - REST_SERVER_PORT=8080
      - SERVICE_NAME=evam
      - OPCUA_SERVER_IP=$OPCUA_SERVER_IP
      - OPCUA_SERVER_PORT=$OPCUA_SERVER_PORT
      - OPCUA_SERVER_USERNAME=$OPCUA_SERVER_USERNAME
      - OPCUA_SERVER_PASSWORD=$OPCUA_SERVER_PASSWORD
      - ENABLE_OPEN_TELEMETRY=true
      - OTEL_COLLECTOR_HOST=${OTEL_COLLECTOR_HOST}
      - OTEL_COLLECTOR_PORT=${OTEL_COLLECTOR_PORT}
      - OTEL_EXPORT_INTERVAL_MILLIS=${OTEL_EXPORT_INTERVAL_MILLIS}
    depends_on:
      - otel-collector
    volumes:
      # - "../resources:/home/pipeline-server/resources/"
      # - "../configs/default/config.json:/home/pipeline-server/config.json"
      - vol_evam_pipeline_root:/var/cache/pipeline_root:uid=1999,gid=1999
      - "../certificates:/MqttCerts:ro"
      - "../Certificates/ssl_server/:/run/secrets/EdgeVideoAnalyticsMicroservice_Server:ro"
      - "../Certificates/model_registry/:/run/secrets/ModelRegistry_Server:ro"
      #  - "../user_scripts/udfs/python:/home/pipeline-server/udfs/python"
      - "/run/udev:/run/udev:ro"
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "./mr_models:/home/pipeline-server/mr_models:rw"
    group_add:
      # render group ID for ubuntu 20.04 host OS
      - "109"
      # render group ID for ubuntu 22.04 host OS
      - "110"
    device_cgroup_rules:
      # Default run - device-cgroup-rule='c 189:* rmw'
      # Selective rules can be applied for deployment
      - 'c 189:* rmw'
      - 'c 209:* rmw'
      - 'a 189:* rwm'
    devices:
      # Following devices under /dev filesystem will be needed based on usecase
      # dri - GPU
      # USB camera devices
      # Selective mount can be done for deployment as mounting whole /dev is not recommended
      - "/dev:/dev"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    environment:
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=$no_proxy,otel-collector,localhost,127.0.0.1
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ../configs/open_telemetry/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.94.0
    container_name: otel-collector
    environment:
      HTTP_PROXY: ${http_proxy}
      HTTPS_PROXY: ${https_proxy}
      NO_PROXY: $no_proxy,prometheus,edge-video-analytics-microservice,localhost,127.0.0.1
    ports:
      - "4317:4317"  # OTLP gRPC receiver (default for metrics)
      - "4318:4318"  # Prometheus scrape target
    volumes:
      - ../configs/open_telemetry/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml  # OpenTelemetry Collector config
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  vol_evam_pipeline_root:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
