#
# Apache v2 license
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

services:
  broker:
    image: eclipse-mosquitto
    hostname: mqtt
    container_name: mqtt_broker
    volumes:
      - ../utils/mosquitto:/mosquitto/config
    ports:
      - "1883:1883"
    networks:
      - app_network

  edge-video-analytics-microservice:
    image: intel/edge-video-analytics-microservice:2.4.0
    hostname: edge-video-analytics-microservice
    container_name: edge-video-analytics-microservice
    read_only: true
    security_opt:
    - no-new-privileges
    privileged: false
    tty: true
    entrypoint: ["./run.sh"]
    ports:
      - '8080:8080'
      - '8554:8554'
    networks:
      - app_network
    environment:
      - ENABLE_RTSP=true
      - RTSP_PORT=8554
      - no_proxy=$no_proxy,${RTSP_CAMERA_IP}
      - http_proxy=$http_proxy
      - https_proxy=$https_proxy
      - RUN_MODE=EVA
      - GENICAM=Balluff
      - GST_DEBUG="1,gencamsrc:2"
      # Default Detection and Classification Device
      - DETECTION_DEVICE=CPU
      - CLASSIFICATION_DEVICE=CPU
      - ADD_UTCTIME_TO_METADATA=true
      - LSFEATURE_NAME="EVAM"
      - HTTPS=false # Make it "true" to enable SSL/TLS secure mode, mount the generated certificates
      - MTLS_VERIFICATION=false # if HTTPS=true, enable/disable client certificate verification for mTLS
      # Model Registry Microservice
      - MR_VERIFY_CERT=/run/secrets/ModelRegistry_Server/ca-bundle.crt
      # Append pipeline name to a publisher topic
      - APPEND_PIPELINE_NAME_TO_PUBLISHER_TOPIC=false
      - REST_SERVER_PORT=8080
    volumes:
      - vol_evam_pipeline_root:/var/cache/pipeline_root:uid=1999,gid=1999
      - "../certificates:/MqttCerts:ro"
      - "../Certificates/ssl_server/:/run/secrets/EdgeVideoAnalyticsMicroservice_Server:ro"
      - "../Certificates/model_registry/:/run/secrets/ModelRegistry_Server:ro"
      - "/run/udev:/run/udev:ro"
      - "/dev:/dev"
      - "/tmp:/tmp"
      - "../mr_models:/home/pipeline-server/mr_models:rw"
    group_add:
      - "109"
      - "110"
    device_cgroup_rules:
    - 'c 189:* rmw'
    - 'c 209:* rmw'
    - 'a 189:* rwm'
    devices:
    - "/dev:/dev"

networks:
  app_network:
    driver: "bridge"

volumes:
  vol_evam_pipeline_root:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
