global:
  proxy:
    no_proxy: <no-proxy>
    http_proxy: <http-proxy>
    https_proxy: <https-proxy>

rerankerService:
  name: reranker
  service:
    type: ClusterIP
    port: 8090
    targetPort: 80
  image:
    repository: ghcr.io/huggingface/text-embeddings-inference
    tag: "cpu-1.5"
    pullPolicy: IfNotPresent
