global:
  proxy:
    no_proxy: <NO_PROXY>
    http_proxy: <HTTP_PROXY>
    https_proxy: <HTTPS_PROXY>

chatqnaui:
  name: chatqna-ui
  image:
    repository: intel/chatqna-ui
    tag: "1.1"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  env:
    APP_ENDPOINT_URL: "/v1/chatqna"
    APP_DATA_PREP_URL: "/v1/dataprep"
