apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.docSumUI.name }}
spec:
  type: {{ .Values.docSumUI.service.type }}
  ports:
    - port: {{ .Values.docSumUI.service.port }}
      targetPort: {{ .Values.docSumUI.service.targetPort }}
  selector:
    app: document-summarization