name: 'License and Namespace Checker'
description: 'Checks license headers and namespace usage in headers'
runs:
  using: 'composite'
  steps:
    - name: Check out edge-ai-libraries repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
      with:
        path: edge-ai-libraries-repo
        persist-credentials: false
        fetch-depth: 0

    - name: Detect changed languages
      id: detect-langs
      run: |
        cd edge-ai-libraries-repo
        if [ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]; then
          git fetch origin main:main
          echo "Fetched main branch"
        fi
        changed_files=$(git diff --name-only main...$GITHUB_SHA -- '*.h' '*.hpp' '*.c' '*.cpp' '*.sh' '*.py' '*.java' '*.js' '*.ts' || true)
        echo "Performed git diff"

        if [ -z "$changed_files" ]; then
          echo "No relevant changed files detected."
          echo "langs=[]" >> $GITHUB_OUTPUT
          exit 0
        fi
        declare -A langmap=( ["c"]=c-cpp ["cpp"]=c-cpp ["h"]=c-cpp ["hpp"]=c-cpp ["py"]=python ["java"]=java-kotlin ["js"]=javascript-typescript ["ts"]=javascript-typescript )
        declare -A langs
        for file in $changed_files; do
          ext="${file##*.}"
          [[ ${langmap[$ext]} ]] && langs[${langmap[$ext]}]=1
        done
        result=$(printf '%s\n' "${!langs[@]}" | sort | jq -R . | jq -s .)
        echo "Detected languages: $result"
        echo "langs=$result" >> $GITHUB_OUTPUT


    - name: Check License header and namespace usage in headers
      shell: bash
      env:
        CHANGED_FILES: ${{ steps.discover-changes.outputs.changed_files }}
      run: |
        if [ -z "${{ env.CHANGED_FILES }}" ]; then
          echo "No new files to scan."
        else
          ./.github/actions/common/license-namespace-checker/run.sh . $CHANGED_FILES
        fi
