name: 'License and Namespace Checker'
description: 'Checks license headers and namespace usage in headers'
inputs:
  changed_files:
    description: 'List of changed files to scan'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check License header and namespace usage in headers
      shell: bash
      run: |
        if [ -z "${{ inputs.changed_files }}" ]; then
          echo "No new files to scan."
        else
          ./.github/actions/common/license-checker/scripts/run.sh ${{ inputs.changed_files }}
        fi