name: 'License and Namespace Checker'
description: 'Checks license headers and namespace usage in headers'
inputs:
  changed_files:
    description: 'List of changed files to scan'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check out edge-ai-libraries repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
      with:
        persist-credentials: false

    - name: Check License header and namespace usage in headers
      shell: bash
      run: |
        if [ -z "${{ inputs.changed_files }}" ]; then
          echo "No new files to scan."
        else
          ./.github/actions/common/license-namespace-checker/run.sh ${{ inputs.changed_files }}
        fi