apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.pvcName }}
  annotations:
    helm.sh/resource-policy: keep 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi