apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.pvcName }}
  {{- if .Values.global.env.keeppvc }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }} 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi