replicaCount: 1

image:
  repository: intel/model-download
  tag: 1.0.0
  pullPolicy: IfNotPresent

env:
  HF_TOKEN: ""
  ENABLED_PLUGINS: "all"

service:
  type: ClusterIP
  port: 8000

resources: {}