global:
  proxy:
    no_proxy: 
    http_proxy: 
    https_proxy: 

replicaCount: 1

image:
  repository: registry/model-download  #provide your registry info here, replace 'registry' with actual registry URL
  tag: 1.1.0
  pullPolicy: IfNotPresent

readinessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 60
    periodSeconds: 30

env:
  HF_TOKEN: ""
  ENABLED_PLUGINS: "all"   #Comma separated list of plugins to enable, or "all"

service:
  type: NodePort
  nodePort: 32000
  port: 8000
