apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egai-ovms-embed-pvc
  {{- if .Values.global.keeppvc }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.egai_ovms_embed_pvc.size }}
