{
 "title": "NPU Dashboard",
 "tags": [ "npumon" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Node", "label": "Node", "query": { "query": "label_values(instance)" } },
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "NPU Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "NPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "npu_monitor_temperature{}", "legendFormat": "NPU: {{dev_id}}" }
   ]
  },
  {
   "title": "NPU Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "npu_monitor_power{}", "legendFormat": "NPU: {{dev_id}}" }
   ]
  },
  {
   "title": "DPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "npu_monitor_freq_hz{}", "legendFormat": "NPU: {{dev_id}}" }
   ]
  },
  {
   "title": "DPU Frequency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "npu_monitor_freq_hz{}", "legendFormat": "NPU: {{dev_id}}" }
   ]
  },
  {
   "title": "NPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "npu_util{} / 100", "legendFormat": "NPU: {{dev_id}}" }
   ]
  },
  {
   "title": "NPU Tile Config",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "npu_tile_config", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "npu_memory_util{} * (1024 * 1024)",
     "legendFormat": "NPU: {{dev_id}}"
    }
   ]
  },
  {
   "title": "NPU Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "npu_memory_bandwidth{} * (1024 * 1024)",
     "legendFormat": "NPU: {{dev_id}}"
    }
   ]
  }
 ]
}