apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-summary-ingestion-models-pvc
  {{- if .Values.global.env.keeppvc }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}  # Prevent Helm from deleting PVC on uninstall
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
