apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "videoingestion.fullname" . }}-pipeline-root
  {{- if .Values.global.env.keeppvc }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
