global:
  proxy:
    no_proxy: <no-proxy>
    http_proxy: <http-proxy>
    https_proxy: <https-proxy>
  EMBEDDING_MODEL_NAME: <embedding-model-name>

teiEmbeddingService:
  name: tei-embedding-service
  image: 
    repository: ghcr.io/huggingface/text-embeddings-inference
    tag: cpu-1.5
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6006
    targetPort: 80
  shm_size: 1g
