name: Simple Video Structurization (D-T-C)
definition: >
  Transportation Proxy Pipeline 3 performs license plate detection on vehicles, enabling automated
  identification and tracking of license plates for transportation analysis and monitoring.
metadata:
  classname: SimpleVideoStructurization
  enabled: false
recording:
  url: "https://videos.pexels.com/video-files/30787543/13168475_1280_720_25fps.mp4"
  filename: license-plate-detection.mp4
parameters:
  run:
    recording_channels: false
  benchmark:
    ai_stream_rate: false
    result_format: "Best Config: {ai} AI streams -> {fps:.2f} FPS"
  inference:
    detection_models:
      - "SSDLite MobileNet V2 (INT8)"
      - "YOLO v5m 416x416 (INT8)"
      - "YOLO v5s 416x416 (INT8)"
      - "YOLO v5m 640x640 (INT8)"
      - "YOLO v10s 640x640 (FP16)"
      - "YOLO v10m 640x640 (FP16)"
      - "YOLO v8 License Plate Detector (FP16)"
    detection_model_default: "YOLO v8 License Plate Detector (FP16)"
    classification_models:
      - "Disabled"
      - "EfficientNet B0 (INT8)"
      - "MobileNet V2 PyTorch (FP16)"
      - "ResNet-50 TF (INT8)"
      - "PaddleOCR (FP16)"
    classification_model_default: "PaddleOCR (FP16)"
