global:
  proxy:
    no_proxy: <no-proxy>
    http_proxy: <http-proxy>
    https_proxy: <https-proxy>
  MINIO_ROOT_USER: <minio-root-user>
  MINIO_ROOT_PASSWORD: <minio-root-password>

dataStore:
  name: datastore
  image:
    repository: intel/object-store
    tag: "1.1.1"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  env:
    MINIO_HOST: minio-server
    MINIO_API_PORT: 9000
    MINIO_ACCESS_KEY: <dummy-user>
    MINIO_SECRET_KEY: <dummy-password>
