global:
  huggingface:
    apiToken: <HUGGINGFACEHUB_API_TOKEN># Set this during installation
  proxy:
    no_proxy: <NO_PROXY>
    http_proxy: <HTTP_PROXY>
    https_proxy: <HTTPS_PROXY>
  POSTGRES_USER: <POSTGRES_USER>
  POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
  EMBEDDING_MODEL_NAME: <EMBEDDING_MODEL_NAME>
  teiEmbeddingService:
    enabled: false
  ovmsEmbeddingService:
    enabled: false

dataprepPgvector:
  name: document-ingestion
  image:
    repository: intel/document-ingestion
    tag: "1.1"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  env:
    PG_CONNECTION_STRING: postgresql+psycopg://
    PORT_DB: 5432/langchain
    INDEX_NAME: intel-rag
    DATASTORE_ENDPOINT_URL: http://datastore
    CHUNK_SIZE: 1500
    CHUNK_OVERLAP: 100
