apiVersion: v1
kind: Service
metadata:
  name: chatqna-core-ui
spec:
  type: {{ .Values.uiService.type }}
  ports:
    - port: {{ .Values.uiService.port }}
      targetPort: 80
  selector:
    app: chatqna-core-ui