apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dataStore.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dataStore.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dataStore.name }}
    spec:
      containers:
        - name: {{ .Values.dataStore.name }}
          image: {{ .Values.dataStore.image.repository }}:{{ .Values.dataStore.image.tag }}
          imagePullPolicy: {{ .Values.dataStore.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.dataStore.service.port }}
          env:
            - name: http_proxy
              value: {{ .Values.global.proxy.http_proxy }}
            - name: https_proxy
              value: {{ .Values.global.proxy.https_proxy }}
            - name: no_proxy
              value: {{ .Values.global.proxy.no_proxy }}
            - name: MINIO_HOST
              value: {{ .Values.dataStore.env.MINIO_HOST }}.{{ .Release.Namespace }}
            - name: MINIO_API_PORT
              value: "9000"
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.global.MINIO_ROOT_USER }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.global.MINIO_ROOT_PASSWORD }}