name: Smart Network Video Recorder (NVR) Proxy Pipeline
definition: >
  The Smart Network Video Recorder (NVR) Proxy Pipeline builds on top of the
  Simple NVR Proxy Pipeline to add support for video analytics on a subset of input channels.
metadata:
  classname: SmartNVRPipeline
  enabled: true
parameters:
  run:
    recording_channels: true
  benchmark:
    ai_stream_rate: true
    result_format: "Best Config: {s} streams ({ai} AI, {non_ai} non_AI) -> {fps:.2f} FPS"
  inference:
    detection_models:
      - "SSDLite MobileNet V2 (INT8)"
      - "YOLO v5m 416x416 (INT8)"
      - "YOLO v5s 416x416 (INT8)"
      - "YOLO v5m 640x640 (INT8)"
      - "YOLO v10s 640x640 (FP16)"
      - "YOLO v10m 640x640 (FP16)"
    detection_model_default: "YOLO v5s 416x416 (INT8)"
    classification_models:
      - "Disabled"
      - "EfficientNet B0 (INT8)"
      - "MobileNet V2 PyTorch (FP16)"
      - "ResNet-50 TF (INT8)"
    classification_model_default: "ResNet-50 TF (INT8)"
