apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "videoingestion.fullname" . }}-pipeline-root
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
