apiVersion: v2
name: chatqna-core
description: A Helm chart for deploying chatqna-core and its UI
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: chatqna-ui
    version: 0.1.0
    repository: "file://common/chatqna"