global:
  proxy:
    http_proxy: 
    https_proxy: 
    no_proxy:
  env:
    MINIO_SERVER:
    MINIO_HOST:
    MINIO_ROOT_USER: 
    MINIO_ROOT_PASSWORD:


audioanalyzer:
  name: audioanalyzer
  image:
    repository: intel/audio-analyzer
    tag: 1.2.0
    pullPolicy: IfNotPresent
  env:
    DEBUG: "false"
    DEFAULT_DEVICE: "cpu"
    MAX_FILE_SIZE: "314572800"
    STORAGE_BACKEND: minio
    ENABLED_WHISPER_MODELS: "small.en,tiny.en,medium.en"
    DEFAULT_WHISPER_MODEL: "small.en"
    USE_FP16: "true"
  service:
    port: 8000
    targetPort: 8000
    type: ClusterIP
  volumeMounts:
    pvcName: audio-analyzer-pvc
    modelsPvcName: audio-analyzer-models-pvc
    egai_audio_analyzer_pvc:
      size: 20Gi
      accessMode: ReadWriteOnce
    egai_audio_analyzer_models_pvc:
      size: 20Gi
      accessMode: ReadWriteOnce

minioServer:
  name: minio-server
  service:
    type: ClusterIP
    port: 9000
    targetPort: 9000