apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rerankerService.name }}
spec:
  ports:
    - port: {{ .Values.rerankerService.service.port }}
      targetPort: {{ .Values.rerankerService.service.targetPort }}
  selector:
    app: {{ .Values.rerankerService.name }}
