global:
  huggingface:
    apiToken: <HUGGINGFACEHUB_API_TOKEN># Set this during installation
  proxy:
    no_proxy: <no-proxy>
    http_proxy: <http-proxy>
    https_proxy: <https-proxy>
  LLM_MODEL: <llm-model>

ovms:
  name: ovms
  image:
    repository: openvino/model_server
    tag: "2025.0"
    pullPolicy: IfNotPresent
  readinessProbe:
    httpGet:
      path: /v2/health/ready
      port: 8300
    initialDelaySeconds: 60
    periodSeconds: 30
  service:
    type: ClusterIP
    port: 8300
    targetPort: 8300
  
  # scriptconfigmap: ovms-configmap.yaml
  env:
    WEIGHT_FORMAT: "fp16"
    model_directory_name: "converted_model"
  script:
    name: "ovms-model-preparation"
