apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ovms.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ovms.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ovms.name }}
    spec:
      initContainers:
        - name: init-script
          image: "python:3.10.12"
          imagePullPolicy: {{ .Values.ovms.image.pullPolicy }}
          command:
              - /bin/sh
              - -c
              - |
                if [ -f /opt/data/models/config.json ]; then
                  echo "Config file found, checking for model conversion."
                  if grep '"name": "{{ .Values.global.LLM_MODEL }}"' /opt/data/models/config.json; then
                    echo "Model already converted, skipping conversion."
                  else
                    echo "Model not converted, running init script. /config/init-script.sh "{{ .Values.global.LLM_MODEL }}" "{{ .Values.ovms.env.WEIGHT_FORMAT }}" "{{ .Values.global.huggingface.apiToken }}""
                    . /config/init-script.sh
                  fi
                else
                  echo "No config.json found, running init script. /config/init-script.sh "{{ .Values.global.LLM_MODEL }}" "{{ .Values.ovms.env.WEIGHT_FORMAT }}" "{{ .Values.global.huggingface.apiToken }}""
                  . /config/init-script.sh
                fi
          args: ["{{ .Values.global.LLM_MODEL}}","{{ .Values.ovms.env.WEIGHT_FORMAT }}","{{ .Values.global.huggingface.apiToken }}","{{ .Values.global.gpu.enabled }}"]
          env:
            - name: http_proxy
              value: {{ .Values.global.proxy.http_proxy }}
            - name: https_proxy
              value: {{ .Values.global.proxy.https_proxy }}
            - name: no_proxy
              value: {{ .Values.global.proxy.no_proxy }}
          volumeMounts:
            - name: scripts-volume
              mountPath: /config
            - name: workspace
              mountPath: /opt/data
      containers:
        - name: {{ .Values.ovms.name }}
          image: "{{- if .Values.global.gpu.enabled -}} {{ .Values.ovms.image.repository }}:{{ .Values.ovms.image.Gputag }} {{- else -}} {{ .Values.ovms.image.repository }}:{{ .Values.ovms.image.tag }}{{- end -}}"
          imagePullPolicy: {{ .Values.ovms.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: {{ .Values.ovms.readinessProbe.httpGet.path }}
              port: {{ .Values.ovms.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.ovms.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ovms.readinessProbe.periodSeconds }}
          ports:
            - containerPort: {{ .Values.ovms.service.port }}
          volumeMounts:
            - name: scripts-volume
              mountPath: /config
            - name: workspace
              mountPath: /opt/data
          env:
            - name: http_proxy
              value: {{ .Values.global.proxy.http_proxy }}
            - name: https_proxy
              value: {{ .Values.global.proxy.https_proxy }}
            - name: no_proxy
              value: {{ .Values.global.proxy.no_proxy }}
            - name: WEIGHT_FORMAT
              value: {{ .Values.ovms.env.WEIGHT_FORMAT }}
          args: ["--port", "9300", "--rest_port", "8300", "--config_path", "/opt/data/models/config.json"]
      {{ if .Values.global.gpu.enabled }}
          resources:
            requests:
              {{ .Values.global.gpu.key}}: 1
            limits:
              {{ .Values.global.gpu.key}}: 1
          devices:
            - name: dri-device
              containerPath: /dev/dri
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
      {{ end }}
      volumes:
        - name: scripts-volume
          configMap:
            name: {{ .Values.ovms.script.name }}
            defaultMode: 0777
      {{ if .Values.global.gpu.enabled }}
        - name: dri-device
          hostPath:
            path: /dev/dri
            type: Directory
        - name: workspace
          persistentVolumeClaim:
            claimName: ovms-gpu-pvc
      {{ else }}
        - name: workspace
          persistentVolumeClaim:
            claimName: ovms-pvc
      {{ end }}
