apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egai-ovms-pvc
  annotations:
    helm.sh/resource-policy: keep  # Prevent Helm from deleting PVC on uninstall
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.egai_ovms_pvc.size }}
