apiVersion: v1
kind: PersistentVolumeClaim
metadata:
{{ if .Values.global.gpu.enabled }}
  name: ovms-gpu-pvc
{{ else }}
  name: ovms-pvc
{{ end }}
  {{- if .Values.global.keeppvc }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.ovms_pvc.size }}
