global:
  proxy:
    no_proxy: <NO_PROXY>
    http_proxy: <HTTP_PROXY>
    https_proxy: <HTTPS_PROXY>
  EMBEDDING_MODEL_NAME: <EMBEDDING_MODEL_NAME>

teiEmbeddingService:
  name: tei-embedding-service
  image: 
    repository: ghcr.io/huggingface/text-embeddings-inference
    tag: cpu-1.5
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6006
    targetPort: 80
  volumes:
    - ./data:/data
  shm_size: 1g
