apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minioServer.name }}
  labels:
    app: {{ include "minioServer.name" . }}
spec:
  type: {{ .Values.minioServer.service.type }}
  ports:
    - name: {{ .Values.minioServer.service.console.portName }}
      port: {{ .Values.minioServer.service.console.port }}
      targetPort: {{ .Values.minioServer.consolePortName }}
    - name: {{ .Values.minioServer.service.api.portName }}
      port: {{ .Values.minioServer.service.api.port }}
      targetPort: {{ .Values.minioServer.apiPortName }}
  selector:
    app: {{ .Values.minioServer.name }}