apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.minioServer.volumeMounts.pvcName }}
  {{- if .Values.global.env.keeppvc }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }} # Prevent Helm from deleting PVC on uninstall
spec:
  accessModes:
    - {{ .Values.minioServer.volumeMounts.egai_minio_pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.minioServer.volumeMounts.egai_minio_pvc.size }}
