apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ovms.name }}
  labels:
    app: {{ include "ovms.name" . }}
spec:
  type: {{ .Values.ovms.service.type }}
  ports:
    - port: {{ .Values.ovms.service.port }}
      targetPort: {{ .Values.ovms.service.targetPort }}
  selector:
    app: {{ .Values.ovms.name }}
