openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /stream_log:
    post:
      summary: Query Chain
      description: >-
        Handles POST requests to the /stream_log endpoint.

        This endpoint receives a question in the form of a JSON payload,
        validates the input,

        and returns a streaming response with the processed chunks of the
        question text.

        Args:
            payload (QuestionRequest): The request payload containing the input question text.

        Returns:
            StreamingResponse: A streaming response with the processed chunks of the question text.

        Raises:
            HTTPException: If the input question text is empty or not provided, a 422 status code is returned.
      operationId: query_chain_stream_log_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The response message
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
          description: List of validation errors
      type: object
      title: HTTPValidationError
      description: Validation error response
    QuestionRequest:
      properties:
        input:
          type: string
          title: Input
          description: The input question text
      type: object
      required:
        - input
      title: QuestionRequest
      description: Request payload containing the input question text
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
          description: Location of the error
        msg:
          type: string
          title: Message
          description: Error message
        type:
          type: string
          title: Error Type
          description: Type of the error
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
      description: Validation error details
