name: Transportation Proxy Pipeline 2 (D-C)
definition: >
  The Transportation Proxy Pipeline 2 (D-C) collects road data to understand road usage,
  and collects additional data for tracking vehicles.
metadata:
  classname: Transportation2Pipeline
  enabled: false
parameters:
  run:
    recording_channels: false
  benchmark:
    ai_stream_rate: false
    result_format: "Best Config: {ai} AI streams -> {fps:.2f} FPS"
  inference:
    detection_models:
      - "SSDLite MobileNet V2 (INT8)"
      - "YOLO v5m 416x416 (INT8)"
      - "YOLO v5s 416x416 (INT8)"
      - "YOLO v5m 640x640 (INT8)"
      - "YOLO v10s 640x640 (FP16)"
      - "YOLO v10m 640x640 (FP16)"
    detection_model_default: "YOLO v5s 416x416 (INT8)"
    classification_models:
      - "EfficientNet B0 (INT8)"
      - "MobileNet V2 PyTorch (FP16)"
      - "ResNet-50 TF (INT8)"
    classification_model_default: "ResNet-50 TF (INT8)"
