name: Transportation Proxy Pipeline 2 (D-C)
definition: >
  The Transportation Proxy Pipeline 2 (D-C) collects road data to understand road usage,
  and collects additional data for tracking vehicles.
metadata:
  classname: Transportation2Pipeline
  enabled: false
recording:
  url: "https://videos.pexels.com/video-files/30787543/13168475_1280_720_25fps.mp4"
  filename: license-plate-detection.mp4
parameters:
  run:
    recording_channels: false
  benchmark:
    ai_stream_rate: false
    result_format: "Best Config: {ai} AI streams -> {fps:.2f} FPS"
  inference:
    detection_models:
      - "TODO"
    detection_model_default: "TODO"
    classification_models:
      - "Disabled"
      - "TODO"
    classification_model_default: "TODO"
