#!/bin/bash

act_expand_modules () {
  local act_name=${1%%,*}
  local -a q=($2); 
  local -A seen=(); 
  local i=0
  while [ $i -lt ${#q[*]} ]; do
    local n=${q[$i]}; i=$((i+1))
    [ -z "${seen[$n]:-}" ] || continue
    seen[$n]=1
    local p=$(declare -F | grep -E -m1 " ${ID_LIKE}_[0-9]+_profile_${n}$" | cut -f3 -d' ')
    [ -z "$p" ] || q+=($($p $act_name "${@:3}"))
  done
  echo "${!seen[*]}"
}

act_extract_modules () {
  local act_name=${1%%,*}
  local all_cmds=($(declare -F | grep -E " subcommand_" | cut -f2- -d_) profile)
  local all_modules=($(declare -F | grep -E " ${ID_LIKE}_[0-9]+_($(IFS='|';echo "${all_cmds[*]}"))_" | cut -f4- -d_))
  local all_module_args=" ${all_modules[*]/#/--} "
  local -A modules=()
  local v
  for v in ${*:2}; do
    [[ " ${all_module_args} " != *" $v "* ]] || break
    [[ " ${all_module_args} " != *" --$v "* ]] || modules[$v]=1
  done
  echo "${!modules[*]}"
}

act_extract_args () {
  local act_name=${1%%,*}
  local module_name=$2
  local act_modules="$3"
  local all_cmds=($(declare -F | grep -E " subcommand_" | cut -f2- -d_) profile)
  local all_modules=($(declare -F | grep -E " ${ID_LIKE}_[0-9]+_($(IFS='|';echo "${all_cmds[*]}"))_" | cut -f4- -d_))
  local all_module_args=" ${all_modules[*]/#/--} "
  local args1=() args2=() i j
  for ((i=4;i<=${#@};i++)); do
    if [[ " ${all_module_args} " = *" ${*:$i:1} "* ]]; then
      for ((j=++i;j<=${#*};j++)); do
        [[ " ${all_module_args} " != *" ${*:$j:1} "* ]] || break
      done
      [ "${*:$((i-1)):1}" != "--${module_name}" ] || args2+=(${*:$i:$((j-i))})
      i=$((j-1))
    elif [[ " ${all_module_args} " != *" --${*:$i:1} "* ]]; then
      args1+=(${*:$i:1})
    fi
  done
  echo "${args1[*]} ${act_modules} -- ${args2[*]}"
}

act_find_deps () {
  local act_name=${1%%,*}
  local -A handlers=()
  local name handler
  for name in $(act_expand_modules $act_name "$(act_extract_modules "$@")" "${@:2}"); do
    handler=$(declare -F | grep -E -m1 " ${ID_LIKE}_[0-9]+_${act_name}_${name}$" | cut -f3 -d' ')
    [ -z "$handler" ] || handlers[$handler]=1
  done
  echo "${!handlers[*]}"
}

act_helpper () {
  local act_name=${1%%,*}
  local act_text="${1#*,}"
  local sort_options="$2"
  shift
  shift

  if [[ " $* " = *" --help "* ]]; then
    local components=($(declare -F | grep -E " ${ID_LIKE}_[0-9]+_${act_name}_" | cut -f4- -d_))
    if [ ${#components[*]} -gt 0 ]; then
      if [ "${act_name}" = "install" ]; then
        echo "${act_name} options:"
        echo "  --reset-<name>  force reinstallation of the component if exit."
        echo
      fi
    fi
    return 0
  fi

  # scan for dependencies
  local handles=($(
    act_find_deps $act_name $(
      # always included modules
      for m in pre_system_scan core_types; do 
        declare -F | grep -q -E " ${ID_LIKE}_[0-9]+_${act_name}_${m}$" && echo $m
      done
    ) "$@"
  ))

  # act in sequence
  if [ ${#handles[@]} -gt 0 ]; then
    if [ "$act_name" = "install" ]; then
      # build license gate
      local -A licenses=() licenses_text=()
      for licenser in ${handles[*]/_install_/_license_}; do
        if declare -F $licenser > /dev/null 2>&1; then
          local license_text="$($licenser "$@")"
          [ -n "$license_text" ] || continue
          local id1=$(echo "$license_text" | awk '/@@LICENSE-ID/{print$2}')
          local name1=$(echo $licenser | cut -f4- -d_)
          licenses[$id1]="${licenses[$id1]:-}$name1,"
          licenses_text[$id1]="$license_text"
        fi
      done
      if [ ${#licenses[*]} -gt 0 ]; then
        for id1 in ${!licenses[*]}; do
          echo "${licenses_text[$id1]}"
          echo "@@LICENSE-COMPONENT $(echo "${licenses[$id1]%,}")"
        done | tee | ensure_license_gate $installer_name "$@"
        if [ $? -ne 0 ]; then
          echo "License declined"
          exit 3
        fi
      fi
    fi

    local rc=0 order=0
    {
      for handler in $(echo "${handles[*]}" | tr ' ' '\n' | sort $sort_options); do
        local name1=$(echo $handler | cut -f4- -d_)
        if [ "$act_name" = "remove" ]; then
          local order1=$(echo $handler | cut -f2 -d_)
          [ "$order" -gt 0 ] || order=$order1
          [ "$order1" -ge "$order" ] || break
        fi
        local invoke_args="$(act_extract_args $act_name $name1 "${handles[*]#${ID_LIKE}_*_${act_name}_}" "$@")"
        if [[ " $* " = *" --dry-run "* ]]; then
          echo "@@COMP $name1"
          echo "Invoke $handler with $invoke_args" 
          echo "@@OK $name1"
        else
          local state_path="$(ensure_project_path)/$installer_name/states/$name1"
          [ "$act_name" = "start" ] && mkdir -p "$state_path"
          echo "@@COMP $name1"
          (
            set -e
            $handler $invoke_args &
            wait -n
          )
          local rc1=$?
          [[ " stop remove " = *" $act_name "* ]] && rm -rf "$state_path"
          if [ $rc1 -eq 0 ]; then
            echo "@@OK $name1"
          else
            echo "@@FAIL $name1"
            rc=$rc1
            [[ " $* " = *" --continue "* ]] || break
          fi
        fi
      done
      if [[ " $* " != *" --dry-run "* ]] && [ $rc -eq 0 ] && declare -F ${ID_LIKE}_10_${act_name}_pre_system_scan > /dev/null 2>&1; then
        echo "@@REPORT SYSTEM SUMMARY"
        ${ID_LIKE}_10_${act_name}_pre_system_scan
      fi
    } > >(
      LOG_FILE="$(ensure_project_path)/$installer_name/$(date +%Y-%m-%d).logs"
      mkdir -p "$(dirname "$LOG_FILE")"
      echo "========== $(date -Ins) ==========" >> "$LOG_FILE"
      echo "@@COMMAND $act_name $*" >> "$LOG_FILE"
      ensure_panelled_logs ${act_text//,/ }
    ) 2>&1
    # wait for background processes
    wait
    return $rc
  else
    echo "Component not found" 1>&2
    exit 3
  fi
}

subcommand_install () {
  act_helpper "install,Installation,Installing,Installed" "" "$@"
}

subcommand_remove () {
  act_helpper "remove,Removal,Removing,Removed" "-r" "$@"
}

subcommand_start () {
  act_helpper "start,Start,Starting,Started" "" "$@"
}

subcommand_stop () {
  [[ " $* " != *" --help "* ]] || return

  local args=("$@") margs=(${*##-*})
  local state_path="$(ensure_project_path)/$installer_name/states"
  [ ${#margs[@]} -eq 0 ] && [ -d "$state_path" ] && args+=($(cd "$state_path"; ls -1))
  act_helpper "stop,Stop,Stopping,Stopped" "-r" "${args[@]}" --continue
}

subcommand_list () {
  [[ " $* " != *" --help "* ]] || return

  echo "Mapping profiles and components..." 1>&2
  local all_cmds=($(declare -F | grep -E " subcommand_" | cut -f2- -d_))
  local all_profiles=($(declare -F | grep -E " ${ID_LIKE}_[0-9]+_profile_" | cut -f3 -d' '))
  local all_modules=($(declare -F | grep -E " ${ID_LIKE}_[0-9]+_($(IFS='|';echo "${all_cmds[*]}"))_" | cut -f2,4- -d_ | sort -r | uniq | cut -f2- -d_))

  {
    if [ ${#all_profiles[@]} -gt 0 ]; then
      echo "List of profiles:"
      local profiler
      for profiler in ${all_profiles[*]}; do
        local profile_name=$(echo $profiler | cut -f4- -d_)
        [[ " ${all_modules[*]} " != *" $profile_name "* ]] || continue
        local profile_cmds=() mname cmd
        for cmd in ${all_cmds[*]}; do
          [[ " bootstrap list setup " != *" $cmd "* ]] || continue
          for mname in $(act_expand_modules $cmd "$($profiler $cmd "$@")" "$@"); do
            if declare -F | grep -q -E " ${ID_LIKE}_[0-9]+_${cmd}_${mname}$"; then
              profile_cmds+=($cmd)
              break
            fi
          done
        done
        echo "|$profile_name|[${profile_cmds[*]}]"
      done
      echo
    fi
  
    if [ ${#all_modules[@]} -gt 0 ]; then
      echo "List of components:"
      local module_name
      for module_name in ${all_modules[*]}; do
        local module_cmds=() mname cmd
        for cmd in ${all_cmds[*]/list/}; do
          for mname in $(act_expand_modules $cmd $module_name "$@"); do
            if declare -F | grep -q -E " ${ID_LIKE}_[0-9]+_${cmd}_${mname}$"; then
              module_cmds+=($cmd)
              break
            fi
          done
        done
        echo "|$module_name|[${module_cmds[*]}]"
      done
      echo
    fi
  } | ensure_columns
}

subcommand_setup () {
  [[ " $* " != *" --help "* ]] || return

  # reconstruct installer
  local installer_misc_functions=()
  if [ ${#installer_misc_functions[@]} -gt 0 ]; then
    local installer=~/.local/bin/$installer_name
    cat > "$installer" <<EOF
#!/bin/bash
$(declare -f ${installer_misc_functions[*]})
$(declare -f $(declare -F | grep -E " (${ID_LIKE}_[0-9]+_|ensure_|act_|subcommand_|main$)" | cut -f3 -d' ' | tr '\n' ' '))
main "\$@"
EOF
    chmod a+rx "$installer"
    echo "Installer reconstructed at $installer"
  fi

  # reconstruct bash completion
  local completion_script=~/.local/share/bash-completion/completions/$installer_name
  mkdir -p "$(dirname "$completion_script")"

  local all_cmds=($(declare -F | grep " subcommand_" | cut -f2- -d_))
  cat > "$completion_script" <<EOF
#!/bin/bash
_${installer_name//-/_}_completion () {
  if (( COMP_CWORD == 1 )); then
    COMPREPLY=(\$(compgen -W "${all_cmds[*]} --help" -- "\$2"))
    return
  fi

  case "\${COMP_WORDS[1]}" in
$(  
    for cmd in ${all_cmds[*]}; do
      [[ " bootstrap list setup " != *" $cmd "* ]] || continue
      local -A all_comps=(["--continue"]="" ["--dry-run"]="")
      local all_modules=($(declare -F | grep -E " ${ID_LIKE}_[0-9]+_${cmd}_" | cut -f4- -d_))
      for profiler in $(declare -F | grep -E " ${ID_LIKE}_[0-9]+_profile_" | cut -f3 -d' '); do
        local pname=$(echo $profiler | cut -f4- -d_)
        [[ " ${all_modules[*]} " != *" $pname "* ]] || continue
        for mname in $($profiler $cmd); do
          declare -F | grep -q -E " ${ID_LIKE}_[0-9]+_${cmd}_${mname}$" && all_comps[$pname]=""
        done
      done
      for mname in ${all_modules[*]}; do
        all_comps[$mname]=""
        [ "$cmd" != "install" ] || all_comps["--reset-$mname"]=""
      done
      echo "  $cmd)"
      echo "    $(declare -p all_comps | sed 's|declare -A |local -A |')"
      echo "    for ((i=2;i<COMP_CWORD;i++)); do unset \"all_comps[\${COMP_WORDS[\$i]}]\"; done"
      echo "    COMPREPLY=(\$(compgen -W \"\${!all_comps[*]}\" -- \"\$2\"))"
      echo "    ;;"
    done
)
  *)
    COMPREPLY=()
    ;;
  esac
}
complete -F _${installer_name//-/_}_completion $installer_name
EOF
  echo "bash completion created at $completion_script"
}

