name: "[DLS] [U22/24] Build dev imgs"
run-name: "[DLS] [U22/24] Build dev imgs (by ${{ github.actor }})"
on:
  workflow_call:
  workflow_dispatch:
permissions: {}

jobs:
  build:
    name: Build dev ${{ matrix.ubuntu_version }} imgs
    runs-on: ubuntu-22.04-16core-64GB
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - path_dev: ./libraries/dl-streamer/docker/devel/ubuntu22/dlstreamer_dev_ubuntu22.Dockerfile
            ubuntu_version: ubuntu22
          - path_dev: ./libraries/dl-streamer/docker/devel/ubuntu24/dlstreamer_dev_ubuntu24.Dockerfile
            ubuntu_version: ubuntu24
    steps:
    - name: Check out edge-ai-libraries repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
      with:
        persist-credentials: false

    - name: Init submodules
      run: |
        git submodule update --init libraries/dl-streamer/thirdparty/spdlog

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #3.10.0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build dev debug img with cache from GHCR
      env:
        dev_debug_img: ghcr.io/${{ github.repository }}/dev-debug-img-${{ matrix.ubuntu_version }}:${{ github.sha }}
        dev_debug_img_cached: ghcr.io/${{ github.repository }}/dev-debug-img-${{ matrix.ubuntu_version }}:buildcache
      run: |
        docker buildx build \
          --load \
          --tag "${dev_debug_img}" \
          --cache-from="${dev_debug_img_cached}" \
          --build-arg BUILD_ARG=Debug \
          -f ${{ matrix.path_dev }} \
          ./libraries/dl-streamer

    # ======================================================== SCANNING PART ========================================================
    - name: Scan Docker image with Trivy
      uses: open-edge-platform/orch-ci/.github/actions/security/trivy@5ea97eb41959d0922ab99956b4db23910f4fb4a2
      with:
        scan_target: "ghcr.io/${{ github.repository }}/dev-debug-img-${{ matrix.ubuntu_version }}:${{ github.sha }}"
        severity: "CRITICAL"
        scan_type: image
        format: json
        report_suffix: ${{ matrix.ubuntu_version }}-dev-img
        scan-scope: all
        timeout: 20m

    - name: Clean up
      env:
        dev_debug_img: ghcr.io/${{ github.repository }}/dev-debug-img-${{ matrix.ubuntu_version }}:${{ github.sha }}
      if: always()
      run: |
        docker rmi ${dev_debug_img} || true
