name: "[DLS] PR workflow"
run-name: "[DLS] PR  workflow (by @${{ github.actor }} via ${{ github.event_name }})"
on:
  push:
    branches:
      - 'main'
    paths:
      - 'libraries/dl-streamer/**'
    paths-ignore:
      - 'libraries/dl-streamer/docs/**'
  pull_request:
    paths:
      - 'libraries/dl-streamer/**'
    paths-ignore:
      - 'libraries/dl-streamer/docs/**'
  workflow_call:
permissions: read-all

jobs:
  build-dev-images:
    name: Build dev img
    uses: ./.github/workflows/dls-build-dev-docker-images.yaml
  
  build-deb-and-img:
    name: Build deb and img
    uses: ./.github/workflows/dls-build-deb-packages-and-images.yaml