name: "[DLS] [U22/24] Build Docker Images"
run-name: "[DLS] [U22/24] Build Docker Images"
on:
  push:
    paths:
      - 'libraries/dl-streamer/**'
  pull_request:
    paths:
      - 'libraries/dl-streamer/**'
permissions: read-all

jobs:
  build:
    name: Build ${{ matrix.image }} image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: ./libraries/dl-streamer/docker/dlstreamer_dev_ubuntu22.Dockerfile
            image: dev-ubuntu22
          - path: ./libraries/dl-streamer/docker/dlstreamer_dev_ubuntu24.Dockerfile
            image: dev-ubuntu24
          - path: ./libraries/dl-streamer/docker/dlstreamer_ubuntu22.Dockerfile
            image: one-binary-ubuntu22
          - path: ./libraries/dl-streamer/docker/dlstreamer_ubuntu24.Dockerfile
            image: one-binary-ubuntu24
    steps:
    - name: Check out edge-ai-libraries repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }} -f ${{ matrix.path }} .

    # - name: Push Docker image
    #   run: |
    #     docker push ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }}

    - name: Save image info
      id: save-image
      run: echo "image=ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }} " >> $GITHUB_ENV

    - name: Create summary
      if: always()
      run: |
        echo "### Docker ${{ matrix.image }} :ship:" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "${{ env.image }}" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY