name: "[PROD] [U22/24] Build and Push Docker Images"
run-name: "[PROD] [U22/24] Build and Push Docker Images"
on:
  push:
    branches:
      - 'dls-ci-docker-images'
    paths:
      - 'libraries/dl-streamer/**'
    paths-ignore:
      - 'libraries/dl-streamer/docs/**'
  pull_request:
    paths:
      - 'libraries/dl-streamer/**'
    paths-ignore:
      - 'libraries/dl-streamer/docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: ./libraries/dl-streamer/docker/dlstreamer_dev_ubuntu22.Dockerfile
            image: dev-ubuntu22
          - path: ./libraries/dl-streamer/docker/dlstreamer_dev_ubuntu24.Dockerfile
            image: dev-ubuntu24
          - path: ./libraries/dl-streamer/docker/dlstreamer_ubuntu22.Dockerfile
            image: one-binary-ubuntu22
          - path: ./libraries/dl-streamer/docker/dlstreamer_ubuntu24.Dockerfile
            image: one-binary-ubuntu24
    steps:
    - name: Check out edge-ai-libraries repository
      uses: actions/checkout@v4.2.0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }} -f ${{ matrix.path }} .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }}

    - name: Save image info
      id: save-image
      run: echo "image=ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }} " >> $GITHUB_ENV

    - name: Create summary
      if: always()
      run: |
        echo "### Docker ${{ matrix.image }} :ship:" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "${{ env.image }}" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY