name: "[DLS] PR workflow"
run-name: "[DLS] PR  workflow (by @${{ github.actor }} via ${{ github.event_name }})"
on:
  push:
    branches:
      - 'trivy-config-scan'
  #   paths:
  #     - 'libraries/dl-streamer/cmake/**'
  #     - 'libraries/dl-streamer/docker/**'
  #     - 'libraries/dl-streamer/include/**'
  #     - 'libraries/dl-streamer/python/**'
  #     - 'libraries/dl-streamer/samples/**'
  #     - 'libraries/dl-streamer/scripts/**'
  #     - 'libraries/dl-streamer/src/**'
  #     - 'libraries/dl-streamer/tests/**'
  #     - 'libraries/dl-streamer/thirdparty/**'
  # pull_request:
  #   paths:
  #     - 'libraries/dl-streamer/cmake/**'
  #     - 'libraries/dl-streamer/docker/**'
  #     - 'libraries/dl-streamer/include/**'
  #     - 'libraries/dl-streamer/python/**'
  #     - 'libraries/dl-streamer/samples/**'
  #     - 'libraries/dl-streamer/scripts/**'
  #     - 'libraries/dl-streamer/src/**'
  #     - 'libraries/dl-streamer/tests/**'
  #     - 'libraries/dl-streamer/thirdparty/**'
  workflow_call:
  workflow_dispatch:
permissions: read-all

jobs:
  build-dev-images:
    name: Build dev imgs
    uses: ./.github/workflows/dls-build-dev-docker-images.yaml

  build-deb-and-img:
    name: Build .deb pkgs and deb imgs
    uses: ./.github/workflows/dls-build-deb-packages-and-images.yaml

  trivy-config-scan:
    name: Scan ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: dlstreamer_ubuntu22
            path: libraries/dl-streamer/docker/onebinary/ubuntu22/dlstreamer_ubuntu22.Dockerfile
            output: reports/dlstreamer_ubuntu22.txt
          - name: dlstreamer_ubuntu24
            path: libraries/dl-streamer/docker/onebinary/ubuntu24/dlstreamer_ubuntu24.Dockerfile
            output: reports/dlstreamer_ubuntu24.txt
          - name: dlstreamer_dev_ubuntu22
            path: libraries/dl-streamer/docker/devel/ubuntu22/dlstreamer_dev_ubuntu22.Dockerfile
            output: reports/dlstreamer_dev_ubuntu22.txt
          - name: dlstreamer_dev_ubuntu24
            path: libraries/dl-streamer/docker/devel/ubuntu24/dlstreamer_dev_ubuntu24.Dockerfile
            output: reports/dlstreamer_dev_ubuntu24.txt
          - name: fedora41
            path: libraries/dl-streamer/docker/devel/fedora41/dlstreamer_dev_fedora41.Dockerfile
            output: reports/fedora41.txt
    uses: ./.github/workflows/trivy-config-mode.yaml
    with:
      dockerfile-path: ${{ matrix.path }}
      trivy-report-format: 'json'
      severity-levels: 'HIGH,CRITICAL'
      output-report-path: ${{ matrix.output }}
      name: ${{ matrix.name }}