#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
name: "[Model Registry] PR workflow"
run-name: "[Model Registry] PR  workflow (by @${{ github.actor }} via ${{ github.event_name }})"
on:
  push:
    branches:
      - main
    paths:
      - 'microservices/model-registry/**'
  pull_request:
    paths:
      - 'microservices/model-registry/**'

jobs:
  modelregistry-unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd microservices/model-registry
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f tests/requirements-tests.txt ]; then pip install -r tests/requirements-tests.txt; fi

      - name: Run tests
        run: |
          echo "Running unit tests"
          cd microservices/model-registry
          if [ -d tests ]; then PYTEST_OUTPUT=$(pytest -vv --cov=src --cov-report=term-missing --cov-report=xml:coverage.xml tests/unit_tests/ 2>&1 || true)
          # echo "$PYTEST_OUTPUT"
          echo "$PYTEST_OUTPUT" > pytest_results.txt
          echo "run_pytest_raw_output<<EOF" >> $GITHUB_OUTPUT
          echo "$PYTEST_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT; fi
        env:
          PYTHONPATH: "${{ github.workspace }}/microservices/model-registry/src"