#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
name: "[Time SeriesAnalytics] Docker Bench Security Scan"
run-name: "[Time Series Analytics] Docker Bench Security Scan workflow (by @${{ github.actor }} via ${{ github.event_name }})"

on:
  workflow_dispatch:
  
jobs:
  DBS_job:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read          # needed for actions/checkout
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: check the system
        run: |
          docker ps &&
          uname -a &&
          docker version && 
          git version && 
          docker compose version

      - name: Checkout docker/docker-bench-security (master)
        uses: actions/checkout@v4
        with:
          repository: docker/docker-bench-security
          ref: master
          path: docker-bench-security
          persist-credentials: false
      
      - name: Build Docker Bench Security
        run: |
          cd docker-bench-security
          docker build --no-cache -t docker-bench-security .

      - name: Build Time Series Analytics microservice
        run: |
          cd microservices/time-series-analytics/docker
          sed -i -e "s|TIME_SERIES_ANALYTICS_IMAGE=.*|TIME_SERIES_ANALYTICS_IMAGE=ia-time-series-analytics-microservice:latest|g" .env
          docker compose build

      - name: Deploy Time Series Analytics microservice
        run: |
          cd microservices/time-series-analytics/docker
          docker compose up -d

      - name: DBS download and scan for Time Series Analytics microservice
        run: |
          cd microservices/time-series-analytics/docker
          docker run --rm --net host --pid host --userns host --cap-add audit_control \
          -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
          -v /etc:/etc:ro \
          -v /usr/bin/containerd:/usr/bin/containerd:ro \
          -v /usr/bin/runc:/usr/bin/runc:ro \
          -v /usr/lib/systemd:/usr/lib/systemd:ro \
          -v /var/lib:/var/lib:ro \
          -v /var/run/docker.sock:/var/run/docker.sock:ro \
          --label docker_bench_security \
          docker-bench-security > dbs_scan_timeseries.txt

      - name: Undeploy Time Series Analytics microservice
        run: |
          cd microservices/time-series-analytics/docker
          docker compose down -v
          
      - name: Upload Scan artifact to Github
        uses: actions/upload-artifact@v4
        with:
          name: DBS_time-series-analytics
          path: microservices/time-series-analytics/docker/dbs_scan_timeseries.txt

                  