name: "[Time Series Analytics] Run weekly automation tests"
run-name: "[Time Series Analytics] Run weekly automation tests"
on:
  schedule:
    - cron: '0 14 * * 5' # 14:00 UTC
  workflow_dispatch:
permissions: {}

jobs:
  time-series-analytics-microservice-weekly:
    name: Weekly-Run TimeSeries Analytics Microservice tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
    steps:
    - name: Check out edge-ai-libraries repository
      uses: actions/checkout@v1
      with:
        persist-credentials: false
        path: edge-ai-libraries-repo
    - name: Runner workspace path
      run: |
        echo "Cleaning up previous run"
        if [ -n "$(docker ps -aq)" ]; then
            docker stop $(docker ps -aq)
        fi
        if [ -n "$(docker ps -aq)" ]; then
            docker rm $(docker ps -aq)
        fi
        docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f

    - name: Run time-series-analytics-microservices automation tests
      run: |
        cd "${{ github.workspace }}"
        cd ./microservices/time-series-analytics/automation_tests
        echo "Running automation tests"
        pip3 install -r functional/requirements.txt
        rm -rf /tmp/test_report/report.html
        pytest -v --html=/tmp/test_report/report.html test_docker.py
    - name: Upload HTML  test report to Github
      uses: actions/upload-artifact@v4
      with:
        name: automation-test-report
        path: /tmp/test_report

    